version: "3.8"
services:
  mysqldb:
#    platform: linux/x86_64 # M1 MAC인 경우
    image: "mysql:8"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "mileage"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "test"
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/mileage?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "test"
      SPRING_DATASOURCE_PASSWORD: "test"
    depends_on:
      - mysqldb
